function Xtable = readdlctableOLM(filename, dataLines)

%% IMPORTFILE Import data from a text file
%  R1RUBISCRRDLCMOBNET100OLM = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  R1RUBISCRRDLCMOBNET100OLM = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  R1RubiScrrDLCmobnet100OLM = importfile("C:\Users\vladi\OneDrive\Documents\MATLAB\labbehavior\Scripts\OLM\R1RubiScrrDLC_mobnet_100_OLM.140223Feb14shuffle1_200000.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Feb-2023 19:42:18

BODYPARTS={'earleftx';
'earlefty';
'earleftl';
'earrightx';	
'earrighty';	
'earrightl';	
'nosex';	
'nosey';	
'nosel';	
'centerx';	
'centery';	
'centerl';	
'lateralleftx';	
'laterallefty';	
'lateralleftl';	
'lateralrightx';	
'lateralrighty';	
'lateralrightl';	
'tailbasex';	
'tailbasey';	
'tailbasel';	
'tailendx';	
'tailendy';	
'tailendl';	
'oa1x';	
'oa1y';	
'oa1l';	
'oa2x';	
'oa2y';	
'oa2l';	
'oa3x';	
'oa3y';	
'oa3l';	
'oa4x';	
'oa4y';	
'oa4l';	
'ob1x';	
'ob1y';	
'ob1l';	
'ob2x';	
'ob2y';	
'ob2l';	
'ob3x';	
'ob3y';	
'ob3l';	
'ob4x';	
'ob4y';	
'ob4l';	
'topx';	
'topy';	
'topl';	
'rightx';	
'righty';	
'rightl';	
'downx';	
'downy';	
'downl';	
'leftx';	
'lefty';	
'leftl'};

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 61);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ['FRAME';BODYPARTS];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Xtable = readtable(filename, opts);

% end