function dataXY = importxypupil(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  NICESHOTGRAYDLCMOBNET100PUPILDETECTORAPR28SHUFFLE1500000 =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  NICESHOTGRAYDLCMOBNET100PUPILDETECTORAPR28SHUFFLE1500000 =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  NiceShotGrayDLCmobnet100PupilDetectorApr28shuffle1500000 = importfile1("F:\Videos Conducta\PUPILA-CASE\NiceShotGrayDLC_mobnet_100_PupilDetectorApr28shuffle1_500000.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-May-2023 14:28:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = ["scorer", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_1", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_2", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_3", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_4", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_5", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_6", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_7", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_8", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_9", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_10", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_11", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_12", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_13", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_14", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_15", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_16", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_17", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_18", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_19", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_20", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_21", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_22", "DLC_mobnet_100_PupilDetectorApr28shuffle1_500000_23"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.VariableNames  = {'frames','pupil_top_X','pupil_top_Y','pupil_top_L','pupil_bot_X','pupil_bot_Y','pupil_bot_L','pupil_right_X','pupil_right_Y','pupil_right_L','pupil_left_X','pupil_left_Y','pupil_left_L','lid_top_X','lid_top_Y','lid_top_L','lid_bot_X','lid_bot_Y','lid_bot_L','corner_right_X','corner_right_Y','corner_right_L','corner_left_X','corner_left_Y','corner_left_L'};
% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dataXY = readtable(filename, opts);

%% Convert to output type
% dataXY = table2array(NiceShotGrayDLCmobnet100PupilDetectorApr28shuffle1500000);
end