Types=categorical({'Chevron';...
     'Complex';...
     'Down Frequency Modulation';...
     'Flat';...
     'Multiple Steps';...
     'Otro';...
     'Reverse Chevron';...
     'Short';...
     'Step Up';...
     'Up Frequency Modulation'});
